#!/usr/bin/env bash
# Stats and Hidden Bar preferences.
set -euo pipefail

# shellcheck source=../lib/common.sh
. "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

# Overridable so tests can write to throwaway domains.
STATS_DOMAIN="${STATS_DOMAIN:-eu.exelban.Stats}"
HIDDENBAR_DOMAIN="${HIDDENBAR_DOMAIN:-com.dwarvesv.minimalbar}"
APP_PREFS_QUIT="${APP_PREFS_QUIT:-1}"

step "App preferences"

if [ "$APP_PREFS_QUIT" = 1 ]; then
  quit_app Stats
  quit_app "Hidden Bar"
fi


# --- Hidden Bar ---

defaults write "$HIDDENBAR_DOMAIN" isAutoStart -bool true
defaults write "$HIDDENBAR_DOMAIN" isShowPreferences -bool false
defaults write "$HIDDENBAR_DOMAIN" useFullStatusBarOnExpandEnabled -bool false
ok "Hidden Bar"


# --- Stats ---

defaults write "$STATS_DOMAIN" LaunchAtLoginNext -bool true

defaults write "$STATS_DOMAIN" Clock_state -bool true
defaults write "$STATS_DOMAIN" Disk_state  -bool false

# Battery glyph plus a mini readout, in one view.
defaults write "$STATS_DOMAIN" Battery_widget -string "battery,mini"
defaults write "$STATS_DOMAIN" Battery_oneView -bool true
defaults write "$STATS_DOMAIN" Battery_battery_color -bool true
defaults write "$STATS_DOMAIN" BAT_mini_label -bool false

# Order of the elements inside the battery widget.
defaults write "$STATS_DOMAIN" Battery_battery_position        -int 0
defaults write "$STATS_DOMAIN" Battery_mini_position           -int 1
defaults write "$STATS_DOMAIN" Battery_label_position          -int 2
defaults write "$STATS_DOMAIN" Battery_barChart_position       -int 3
defaults write "$STATS_DOMAIN" Battery_batteryDetails_position -int 4

# JSON in a data value. Decoded:
#   [{"id":"E4F2E290-6FD9-42E4-98A0-09C1B72918E6","enabled":true,
#     "name":"Local time","format":"E, MMM d    HH:mm:ss","tz":"local"}]
# The id is a local widget identifier generated by Stats, not an account one.
defaults write "$STATS_DOMAIN" Clock_list -data \
  5b7b226964223a2245344632453239302d364644392d343245342d393841302d303943314237323931384536222c22656e61626c6564223a747275652c226e616d65223a224c6f63616c2074696d65222c22666f726d6174223a22452c204d4d4d20642020202048483a6d6d3a7373222c22747a223a226c6f63616c227d5d
ok "Stats"

reload_prefs
